# Generated by Django 5.2.5 on 2025-09-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Viesti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nimi', models.CharField(max_length=100)),
                ('sahkoposti', models.EmailField(max_length=254)),
                ('aihe', models.CharField(max_length=200)),
                ('viesti', models.TextField()),
                ('luotu', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
