# Generated by Django 5.2.5 on 2025-09-15 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kontaktilomake', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viesti',
            old_name='aihe',
            new_name='paikkakunta',
        ),
    ]
