# Generated by Django 5.2.5 on 2025-09-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kontaktilomake', '0002_rename_aihe_viesti_paikkakunta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etusivukuva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
