# Generated by Django 5.2.5 on 2025-09-24 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kontaktilomake', '0003_etusivukuva'),
    ]

    operations = [
        migrations.AddField(
            model_name='etusivukuva',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
