# Generated by Django 5.2.5 on 2025-10-01 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kontaktilomake', '0004_etusivukuva_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Karttakuva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
    ]
