# Generated by Django 5.2.5 on 2025-10-01 14:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kontaktilomake', '0005_karttakuva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karttakuva',
            name='url',
            field=models.CharField(max_length=2000, validators=[django.core.validators.URLValidator()]),
        ),
    ]
