# Generated by Django 5.2.5 on 2025-10-06 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kontaktilomake', '0006_alter_karttakuva_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Osoite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
